FROM node:22.17.0
WORKDIR /usr/local/app
RUN npm install --audit false --fund false -g npm@11.4.2
COPY ./package.json .
COPY ./package-lock.json .
RUN npm ci --audit false --fund false
COPY . .
RUN npx vite build --sourcemap
EXPOSE 5174
CMD ["npx", "vite", "preview", "--port", "5174"]
